name: Keep Kaggle Alive
on:
  schedule:
    - cron: '0 */9 * * *' # Har 9 ghante baad chalega
  workflow_dispatch: # Manual run ke liye

jobs:
  update-kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Run Kaggle Kernel
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          # Notebook ko push/restart karne ki command
          kaggle kernels push -p .
